using System.IO;
using System.Net.Http;
using System.Security.Cryptography;
using System.Text;
using System.Threading;
using Microsoft.Extensions.Logging;
using NAudio.Wave;

namespace RimeTts;

public sealed class GttsViaHttpTts(
	HttpClient Http,
	OptTts Opt,
	ILogger<GttsViaHttpTts> Log
):ITts{
	private readonly SemaphoreSlim _playLock = new(1, 1);

	public async Task<IPlayState> GenEtPlay(IReqGenEtPlay Req, CT Ct){
		if(!OperatingSystem.IsWindows()){
			throw new PlatformNotSupportedException("gTTS playback is implemented for Windows only");
		}

		var text = Req.Text?.Trim() ?? "";
		if(text.Length == 0){
			throw new ArgumentException("tts text is empty", nameof(Req));
		}

		Directory.CreateDirectory(Opt.OutputDir);

		var filePath = Path.Combine(Opt.OutputDir, $"gtts_{HashHex(text)}.mp3");
		if(!File.Exists(filePath)){
			var lang = Req.Language?.Trim() is { Length: > 0 } langVal ? langVal : "en";
			await GenerateWithGttsHttp(text, lang, filePath, Ct);
		}

		await _playLock.WaitAsync(Ct);
		var startAt = DateTimeOffset.UtcNow;
		try{
			await PlayMp3WindowsAsync(filePath, Ct);
		}
		finally{
			_playLock.Release();
		}
		var endAt = DateTimeOffset.UtcNow;

		Log.LogInformation("tts played. file={AudioFile}; durationMs={Duration}", filePath, (endAt - startAt).TotalMilliseconds);
		return new PlayState{
			AudioFile = filePath,
			StartedAtUtc = startAt,
			EndedAtUtc = endAt,
		};
	}

	private static str HashHex(str text){
		var bytes = SHA256.HashData(Encoding.UTF8.GetBytes(text));
		return Convert.ToHexString(bytes).ToLowerInvariant();
	}

	private async Task GenerateWithGttsHttp(str text, str lang, str outMp3Path, CT Ct){
		var chunks = SplitText(text, 180);
		await using var outFs = new FileStream(outMp3Path, FileMode.Create, FileAccess.Write, FileShare.Read);
		for(var i = 0; i < chunks.Count; i++){
			Ct.ThrowIfCancellationRequested();
			var chunk = chunks[i];
			var url = $"https://translate.googleapis.com/translate_tts?ie=UTF-8&client=tw-ob&tl={Uri.EscapeDataString(lang)}&q={Uri.EscapeDataString(chunk)}";
			using var req = new HttpRequestMessage(HttpMethod.Get, url);
			req.Headers.UserAgent.ParseAdd("Mozilla/5.0");
			using var resp = await Http.SendAsync(req, HttpCompletionOption.ResponseHeadersRead, Ct);
			resp.EnsureSuccessStatusCode();
			await using var inStream = await resp.Content.ReadAsStreamAsync(Ct);
			await inStream.CopyToAsync(outFs, Ct);
		}
		await outFs.FlushAsync(Ct);
		Log.LogDebug("gtts mp3 generated by http. chunks={ChunkCount}; file={File}", chunks.Count, outMp3Path);
	}

	private static List<str> SplitText(str text, i32 maxChars){
		var raw = text.Trim();
		if(raw.Length <= maxChars){
			return new List<str>{ raw };
		}

		var result = new List<str>();
		var sb = new StringBuilder();
		foreach(var ch in raw){
			sb.Append(ch);
			if(sb.Length >= maxChars || IsBoundary(ch)){
				result.Add(sb.ToString());
				sb.Clear();
			}
		}
		if(sb.Length > 0){
			result.Add(sb.ToString());
		}
		return result;
	}

	private static bool IsBoundary(char c){
		return c is '。' or '！' or '？' or '；' or '，' or '.' or '!' or '?' or ';' or ',';
	}

	private static Task PlayMp3WindowsAsync(str mp3Path, CT Ct){
		if(!OperatingSystem.IsWindows()){
			throw new PlatformNotSupportedException("windows only");
		}

		return Task.Run(() => {
			Ct.ThrowIfCancellationRequested();
			using var stream = File.OpenRead(mp3Path);
			using WaveStream reader = new Mp3FileReader(stream);
			using var waveOut = new WaveOutEvent();
			waveOut.Init(reader);
			waveOut.Play();

			while(waveOut.PlaybackState == PlaybackState.Playing){
				Ct.ThrowIfCancellationRequested();
				Thread.Sleep(100);
			}
		}, Ct);
	}
}
